### PR TITLE
fix: rewrite mariadb default value

### PR DESCRIPTION
**Pull request by a631807682**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

close https://github.com/go-gorm/gorm/issues/5324

### CODE REVIEW

**Comment by jinzhu** [comment]
Maybe we can add a field like `DontSupportRenameIndex` to `Config`, and set its value during initialization?

**Comment by a631807682** [comment]
@jinzhu  I'm not sure if I understand what you mean, I changed it like this.

**Comment by jinzhu** [comment]
I just tested the reported issue https://github.com/go-gorm/playground/pull/453 on the latest mariadb, seems it doesn't occur anymore? can you confirm?

**Comment by a631807682** [comment]
@jinzhu  https://github.com/go-gorm/playground/pull/453 can not describe the problem.

Here is an example
```go
func TestUniqueColumn(t *testing.T) {
	if DB.Dialector.Name() != "mysql" {
		return
	}

	type UniqueTest struct {
		ID   string `gorm:"primary_key"`
		Name string `gorm:"unique"`
	}

	var err error
	err = DB.Migrator().DropTable(&UniqueTest{})
	if err != nil {
		t.Errorf("DropTable err:%v", err)
	}

	err = DB.AutoMigrate(&UniqueTest{})
	if err != nil {
		t.Fatalf("AutoMigrate err:%v", err)
	}

	err = DB.AutoMigrate(&UniqueTest{})
	if err != nil {
		t.Fatalf("AutoMigrate err:%v", err)
	}

	if !DB.Migrator().HasIndex(&UniqueTest{}, "name") {
		t.Fatalf("dose not has unique name")
	}

	if DB.Migrator().HasIndex(&UniqueTest{}, "name_2") {
		t.Fatalf("has repeat unique name")
	}
}

```

**Comment by jinzhu** [comment]
Merged in this commit, https://github.com/go-gorm/mysql/commit/7ac57a7b322d438a0389fd211895ca558665abb8

Thank you for your PR.

**Pull request closed without merging**
