### PR TITLE
feat: deal with the unique field migrator

### PR DESCRIPTION
**Pull request by Icemap**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### What did this pull request do?

To handle the `AlterColumn()`, because TiDB can't change column constraint.

### CODE REVIEW

**Comment by jinzhu** [comment]
Maybe we can add a `DontSupportRenameColumnUnique` field to `Config`, and during initialize, set it to true if `dialector.ServerVersion` contains `TiDB`?

And in the `AlterColumn` method just remove the `Unique` from the `FullDataType` if `DontSupportRenameColumnUnique` is true?

**Comment by Icemap** [comment]
Sure. But it would be taken time. Because I have a little bit thing need to develop from the company. I'll come back here maybe next week.

**Comment by Icemap** [comment]
> Maybe we can add a `DontSupportRenameColumnUnique` field to `Config`, and during initialize, set it to true if `dialector.ServerVersion` contains `TiDB`?
> 
> And in the `AlterColumn` method just remove the `Unique` from the `FullDataType` if `DontSupportRenameColumnUnique` is true?

Hi @jinzhu, I already make it done. PTAL again.

**Comment by Icemap** [comment]
Continue for https://github.com/go-gorm/gorm/pull/6014

**Pull request merged**
