### PR TITLE
distinguish between schema.Time and tag time

### PR DESCRIPTION
**Pull request by black-06**
- [x] Do only one thing
- [x] Non breaking API changes
- [ ] Tested

### What did this pull request do?

fix https://github.com/go-gorm/gorm/issues/6033

### User Case Description

```go
type Test struct {
    Date time.Time `gorm:"type:date"`
    Time time.Time `gorm:"type:time"`
    DefaultDateTime time.Time
}
```
```sql
CREATE TABLE `tests` (`date` date,`time` time,`default_date_time` datetime)
```

### CODE REVIEW

**Review by a631807682 — COMMENTED** [review]
Not only time, but actually all types have the same problem, can we skip to `getSchemaCustomType`, if the tag `type` is specified without specifying `precision`, `size`?
If so, we only need to add a field in `schema.Field` to identify it

https://github.com/go-gorm/sqlserver/pull/86

**Comment by black-06** [comment]
So,  we need to create a new tag in gorm and then upgrade dirver's dependence?

**Comment by a631807682** [comment]
> So, we need to create a new tag in gorm and then upgrade dirver's dependence?

I think so

**Comment by black-06** [comment]
> > So, we need to create a new tag in gorm and then upgrade dirver's dependence?
> 
> I think so

Okay

**Pull request closed without merging**
