### PR TITLE
feat: Open support mysql.Config

### PR DESCRIPTION
**Pull request by demoManito**
- [x] Do only one thing
- [x] Non breaking API changes
- [x] Tested

### CODE REVIEW

**Review by a631807682 — COMMENTED** [review]
Is it similar to New?

**Comment by a631807682** [comment]
> > Is it similar to New?
> 
> Open() initializes through DSN, while New() initializes more configuration items

After https://github.com/go-gorm/mysql/pull/113 merged they don't have much difference for me

**Comment by demoManito** [comment]
> > > Is it similar to New?
> > 
> > 
> > Open() initializes through DSN, while New() initializes more configuration items
> 
> After #113 merged they don't have much difference for me

Yes, but for me, when using Open, I prefer to initialize the connection through DSNConfig, which is more accurate

**Comment by jinzhu** [comment]
Maybe better to only use the `New` method to do this, going to close this PR.

Thank you.

**Comment by demoManito** [comment]
> Maybe better to only use the `New` method to do this, going to close this PR.
> 
> Thank you.

OK

**Pull request closed without merging**
